import { test, expect } from '@playwright/test'

async function openBuilder(page) {
  await page.getByRole('button', { name: 'Reconstruct', exact: true }).click()
  await page.getByRole('button', { name: 'Workflow Builder', exact: true }).click()
  return page.getByRole('dialog', { name: 'Workflow Builder', exact: true })
}

test('new project workflow supports editing, reordering, templates and persistence', async ({ page }, testInfo) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Object capture', exact: false }).click()
  await page.getByRole('button', { name: 'Create project', exact: true }).click()
  const dialog = await openBuilder(page)
  await expect(dialog.getByText('Build your workflow', { exact: true })).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Run workflow', exact: true })).toBeDisabled()
  await dialog.getByLabel('Workflow name', { exact: true }).fill('My sparse workflow')
  await dialog.getByLabel('Workflow name', { exact: true }).press('Tab')
  await dialog.getByRole('button', { name: 'Add Detect Features', exact: true }).click()
  await dialog.getByRole('button', { name: 'Match Features Automatic', exact: true }).click()
  await dialog.getByRole('button', { name: 'Sparse Model Automatic', exact: true }).click()
  await expect(dialog.locator('.workflow-block')).toHaveCount(3)
  await expect(dialog.getByText('Detect Features: requires images', { exact: true })).toBeVisible()
  await dialog.getByRole('combobox', { name: 'Preset', exact: true }).selectOption('high')
  await dialog.locator('.workflow-block').last().getByTitle('Move up', { exact: true }).click()
  await expect(dialog.locator('.workflow-block').nth(1)).toContainText('Sparse Model')
  await dialog.locator('.workflow-block').nth(1).getByTitle('Move down', { exact: true }).click()
  await expect(dialog.locator('.workflow-block').last()).toContainText('Preset: high')
  await page.screenshot({ path: testInfo.outputPath('builder-desktop.png') })
  await dialog.getByRole('button', { name: 'Save template', exact: true }).click()
  await dialog.getByRole('button', { name: 'Recipe', exact: true }).click()
  await expect(dialog.locator('textarea')).toHaveValue(/workflow "My sparse workflow"[\s\S]*detect-features[\s\S]*match-features[\s\S]*reconstruct/)
  await dialog.getByRole('button', { name: 'Blocks', exact: true }).click()
  await page.setViewportSize({ width: 1024, height: 768 })
  await expect(dialog.getByRole('combobox', { name: 'Preset', exact: true })).toBeVisible()
  await dialog.getByRole('combobox', { name: 'Preset', exact: true }).selectOption('low')
  await expect(dialog.locator('.workflow-block').last()).toContainText('Preset: low')
  await page.screenshot({ path: testInfo.outputPath('builder-compact.png') })
  await dialog.getByRole('button', { name: 'New', exact: true }).click()
  await expect(dialog.getByText('Build your workflow', { exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: 'My sparse workflow', exact: true }).click()
  await expect(dialog.locator('.workflow-block')).toHaveCount(3)
  await expect(dialog.locator('.workflow-block').last()).toContainText('Preset: high')
  // Wait for real OPFS writes, then verify the same app restore path users take.
  await expect.poll(() => page.evaluate(async () => {
    const { readIndex, loadWorkflows } = await import('/src/utils/opfs.js')
    const index = await readIndex()
    const data = await loadWorkflows(index.lastOpenedId)
    return data?.workflows?.length
  })).toBe(3)
  await page.reload()
  await page.getByText('My Project', { exact: true }).click()
  const restored = await openBuilder(page)
  await expect(restored.locator('.workflow-block')).toHaveCount(3)
  await expect(restored.getByLabel('Workflow name', { exact: true })).toHaveValue('My sparse workflow')
  expect(errors).toEqual([])
})

test('interactive workflow pauses and records a completed run', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Object capture', exact: false }).click()
  await page.getByRole('button', { name: 'Create project', exact: true }).click()
  const dialog = await openBuilder(page)
  await dialog.getByRole('button', { name: 'Quality Report Interactive', exact: true }).click()
  await dialog.getByRole('button', { name: 'Run workflow', exact: true }).click()
  const report = page.getByRole('dialog', { name: 'Quality Report', exact: true })
  await expect(report).toBeVisible()
  await report.getByRole('button', { name: 'Close', exact: true }).first().click()
  await expect(dialog.getByText('Waiting for you', { exact: true })).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'New', exact: true })).toBeDisabled()
  await dialog.getByRole('button', { name: 'Mark complete & continue', exact: true }).click()
  await expect(dialog.locator('.run-row')).toContainText('completed')
  await expect(dialog.locator('.workflow-block .status')).toHaveText('completed')
})
