// Pure exporters: turn reconstruction / product data into standard interchange
// formats (bytes or text). No DOM/Blob here — the UI layer wraps the return value
// in a Blob and triggers the download (see utils/download.js).

import { writeGeoTiff, geoKeysForEpsg } from './geotiff.js'

// ── Point cloud → PLY ────────────────────────────────────────────────────────
// points: [{ x, y, z, color?: [r,g,b] (0–255) }]. opts: { binary = true, color =
// true }. Binary returns a Uint8Array (little-endian body); ASCII returns a string.
export function cloudToPly(points, { binary = true, color = true } = {}) {
  const n = points.length
  const props = 'property float x\nproperty float y\nproperty float z\n' +
    (color ? 'property uchar red\nproperty uchar green\nproperty uchar blue\n' : '')
  const header =
    'ply\n' +
    `format ${binary ? 'binary_little_endian' : 'ascii'} 1.0\n` +
    'comment generated by websfm\n' +
    `element vertex ${n}\n` + props + 'end_header\n'

  if (!binary) {
    const lines = new Array(n)
    for (let i = 0; i < n; i++) {
      const p = points[i]
      let s = `${p.x} ${p.y} ${p.z}`
      if (color) { const c = p.color || [200, 200, 200]; s += ` ${byte(c[0])} ${byte(c[1])} ${byte(c[2])}` }
      lines[i] = s
    }
    return header + lines.join('\n') + '\n'
  }

  const headerBytes = new TextEncoder().encode(header)
  const STRIDE = color ? 15 : 12 // 3×f32 (12) [+ 3×u8 (3)]
  const out = new Uint8Array(headerBytes.length + n * STRIDE)
  out.set(headerBytes, 0)
  const dv = new DataView(out.buffer, headerBytes.length)
  for (let i = 0; i < n; i++) {
    const p = points[i]
    const o = i * STRIDE
    dv.setFloat32(o, p.x, true)
    dv.setFloat32(o + 4, p.y, true)
    dv.setFloat32(o + 8, p.z, true)
    if (color) {
      const c = p.color || [200, 200, 200]
      dv.setUint8(o + 12, byte(c[0])); dv.setUint8(o + 13, byte(c[1])); dv.setUint8(o + 14, byte(c[2]))
    }
  }
  return out
}

const byte = (v) => Math.max(0, Math.min(255, Math.round(v ?? 0)))

// ── Reconstruction → JSON (cameras + tracks) ─────────────────────────────────
// cameras: [{ uuid, R, t, K? }], points: [{ x, y, z, color?, views? }]. Camera
// centres (C = −Rᵀt) are precomputed for convenience. Returns a plain object.
export function reconstructionToJson(cameras, points, crs = 'local') {
  return {
    format: 'websfm-model',
    version: 1,
    crs,
    cameras: cameras.map((c) => ({
      uuid: c.uuid,
      R: c.R,
      t: c.t,
      K: c.K ? { fx: c.K.fx, fy: c.K.fy, cx: c.K.cx, cy: c.K.cy } : null,
      center: cameraCenter(c.R, c.t),
    })),
    points: points.map((p) => ({
      x: p.x, y: p.y, z: p.z,
      color: p.color ?? null,
      views: p.views ?? [],
    })),
  }
}

// Camera centre in world coords: C = −Rᵀ·t (R row-major, t = [x,y,z]).
function cameraCenter(R, t) {
  if (!R || !t) return null
  return [
    -(R[0][0] * t[0] + R[1][0] * t[1] + R[2][0] * t[2]),
    -(R[0][1] * t[0] + R[1][1] * t[1] + R[2][1] * t[2]),
    -(R[0][2] * t[0] + R[1][2] * t[1] + R[2][2] * t[2]),
  ]
}

// ── DEM → ESRI ASCII grid (.asc) ─────────────────────────────────────────────
// dem: { width, height, gsd, originX (left), originY (top), data:Float32Array
// (row-major, top→bottom; NaN = nodata) }. Dependency-free, float-preserving, and
// read by QGIS/ArcGIS/GDAL. Pair with a .prj carrying the CRS.
export function demToAsciiGrid(dem, { nodata = -9999 } = {}) {
  const { width, height, gsd, originX, originY, data } = dem
  const yllcorner = originY - height * gsd
  const head =
    `ncols ${width}\n` +
    `nrows ${height}\n` +
    `xllcorner ${originX}\n` +
    `yllcorner ${yllcorner}\n` +
    `cellsize ${gsd}\n` +
    `NODATA_value ${nodata}\n`
  // Row 0 is the northernmost (top) row, which is exactly what ASCII grid wants.
  const rows = new Array(height)
  for (let r = 0; r < height; r++) {
    const row = new Array(width)
    for (let c = 0; c < width; c++) {
      const v = data[r * width + c]
      row[c] = Number.isFinite(v) ? v : nodata
    }
    rows[r] = row.join(' ')
  }
  return head + rows.join('\n') + '\n'
}

// ── DEM → GeoTIFF (single-band float32) ──────────────────────────────────────
// NaN holes are written as `nodata` and flagged via the GDAL_NODATA tag. crs:
// { code: number|null, geographic: boolean } — the EPSG code goes in the GeoKeys.
export function demToGeoTiff(dem, { crs = {}, nodata = -9999 } = {}) {
  const { width, height, gsd, originX, originY, data } = dem
  const buf = new Float32Array(width * height)
  for (let i = 0; i < buf.length; i++) buf[i] = Number.isFinite(data[i]) ? data[i] : nodata
  return writeGeoTiff({
    width, height,
    samples: [{ bits: 32, format: 3 }],
    photometric: 1, extraSamples: null,
    data: new Uint8Array(buf.buffer),
    pixelScale: [gsd, gsd, 0],
    tiepoint: [0, 0, 0, originX, originY, 0],
    geoKeys: geoKeysForEpsg(crs.code, crs.geographic),
    gdalNoData: nodata,
  })
}

// ── Ortho → GeoTIFF (RGBA) ───────────────────────────────────────────────────
// ortho: { width, height, rgba:Uint8Array (w·h·4) }. geo carries the DEM's
// geotransform (ortho shares the DEM grid). crs as in demToGeoTiff.
export function orthoToGeoTiff(ortho, geo, { crs = {} } = {}) {
  const { width, height, rgba } = ortho
  const { gsd, originX, originY } = geo
  const data = rgba instanceof Uint8Array ? rgba : new Uint8Array(rgba.buffer, rgba.byteOffset, rgba.byteLength)
  return writeGeoTiff({
    width, height,
    samples: [0, 1, 2, 3].map(() => ({ bits: 8, format: 1 })),
    photometric: 2, extraSamples: [2], // unassociated alpha
    data,
    pixelScale: [gsd, gsd, 0],
    tiepoint: [0, 0, 0, originX, originY, 0],
    geoKeys: geoKeysForEpsg(crs.code, crs.geographic),
  })
}

// ── Raster world file (.wld / .pgw) for a georeferenced image ─────────────────
// geo: { gsd, originX (left corner), originY (top corner) }. Six lines; lines 5–6
// are the CENTRE of the upper-left pixel (world-file convention).
export function rasterWorldFile(geo) {
  const { gsd, originX, originY } = geo
  return [
    gsd,               // A: x pixel size
    0,                 // D: rotation (y)
    0,                 // B: rotation (x)
    -gsd,              // E: y pixel size (negative: rows go south)
    originX + gsd / 2, // C: x of upper-left pixel centre
    originY - gsd / 2, // F: y of upper-left pixel centre
  ].join('\n') + '\n'
}
